### ISSUE TITLE
Question about cast in Slotted Page

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [pfent/moderndbs#5]
I would like to ask in this function `char *SlottedPage::getSlotData(uint16_t slotId);`
Why you cast the `SlottedPage` to a `char*`:  
```c++
const auto ptrBase = reinterpret_cast<char *>(this);
```
Thanks

**Comment by pfent** [comment]
This slotted page is basically a wrapper around 16 KB raw memory.
The `this` pointer points to the start of this chunk of bytes, from which the offset is calculated *in bytes*.

To get a pointer to this slot data, I need to calculate this offset pointer.
`this + offset` would be incorrect, because the pointer arithmetic depends on the underlying type, which is maybe more visible in the equivalent array notation: `&this[offset]`. For each +1 on the this pointer, we move several bytes (`sizeof(SlottedPage)`) in memory.

Instead, I want to move the pointer by a number of bytes and therefore cast the this pointer to a `char*`

**Comment by cakebytheoceanLuo** [comment]
OK. I get your point to simply to pointer to interval 1 Byte.
This `char*` is not depending on our data type, which is in this case coincidentally also `char*`.
Q) So with this intention, we would also try with `const auto ptrBase = reinterpret_cast<int8_t *>(this);`, is that true?

**Comment by pfent** [comment]
Yes, you're right.
Using anything byte-like would be sufficient, probably a `std::byte*` would be the most fitting, but `char*` or `int8_t*` also works :man_shrugging:
